server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service-route
            uri: lb://user-review-service
            predicates:
              - Path=/api/v1/users/**

          - id: review-service-route
            uri: lb://user-review-service
            predicates:
              - Path=/api/v1/reviews/**

          - id: recommendation-service-route
            uri: lb://user-review-service
            predicates:
              - Path=/api/v1/recommendations/**

          - id: restaurant-service-route
            uri: lb://restaurant-service
            predicates:
              - Path=/api/v1/restaurants/**

management:
  zipkin:
     tracing:
        endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

